name: asset_shield
description: "A new Flutter project with clean architecture"
publish_to: "none"

version: 0.1.0+3

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Routing
  go_router: ^17.0.0

  # HTTP Client
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0

  # UI Utilities
  flutter_screenutil: ^5.9.3
  bot_toast: ^4.1.3
  flutter_easyloading: ^3.0.5
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  # Splash Screen
  flutter_native_splash: ^2.4.7

  # Code Generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_gen_runner: ^5.12.0

  # Secure Storage
  flutter_secure_storage: ^9.2.4

  # JWT Decoder
  jwt_decoder: ^2.0.1

  # Environment Variables
  flutter_dotenv: ^6.0.0

  # Internationalization
  intl: ^0.20.2

  # Other Utilities
  cupertino_icons: ^1.0.8
  flutter_typeahead: ^5.2.0
  blur: ^4.0.2
  lottie: ^3.3.2
  infinite_scroll_pagination: ^5.1.1
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.2
  file_picker: ^10.3.7
  permission_handler: ^12.0.1
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0
  custom_lint:
  riverpod_lint: ^3.0.3 # keep in sync with riverpod version

  # Code Generation
  build_runner: ^2.10.3
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

flutter_native_splash:
  color: "#FFFFFF"
  android: true
  ios: true
  android_12:
    icon_background_color: "#FFFFFF"
  web: false